---
# ibmcloud-create-ai-cluster tasks

- name: Set empty static network configuration
  set_fact:
    static_network_config: []

- name: SNO Cluster Creation
  block:
  - name: SNO - Populate static network configuration with SNO node
    include_role:
      name: create-ai-cluster
      tasks_from: static_network_config.yml
    loop: "{{ groups['sno'] }}"

  - name: SNO - Set cluster_name
    set_fact:
      cluster_name: "{{ groups['sno'][0] }}"

  - name: SNO - Create cluster
    uri:
      url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters"
      method: POST
      body_format: json
      status_code: [201]
      return_content: true
      body: {
          "name": "{{ cluster_name }}",
          "openshift_version": "{{ openshift_version }}",
          "high_availability_mode": "None",
          "base_dns_domain": "{{ base_dns_name }}",
          "cluster_network_cidr": "{{ cluster_network_cidr }}",
          "cluster_network_host_prefix": "{{ cluster_network_host_prefix }}",
          "service_network_cidr": "{{ service_network_cidr }}",
          "pull_secret": "{{ pull_secret | to_json }}",
          "ssh_public_key": "{{ lookup('file', ssh_public_key_file) }}",
          "additional_ntp_source": "{{ bastion_controlplane_ip if (lab in cloud_labs) or use_bastion_registry else labs[lab]['ntp_server'] }}"
      }
    register: create_cluster_return

  - name: SNO - Add entries in /etc/hosts
    blockinfile:
      path: "/etc/hosts"
      backup: true
      block: |
        {{ hostvars[cluster_name]['ip'] }} api.{{ cluster_name }}.{{ base_dns_name }}
        {{ hostvars[cluster_name]['ip'] }} api-int.{{ cluster_name }}.{{ base_dns_name }}
        {% for route in etc_hosts_ingress_routes %}
        {{ hostvars[cluster_name]['ip'] }} {{ route }}.apps.{{ cluster_name }}.{{ base_dns_name }}
        {% endfor %}
      insertafter: "EOF"
      marker: "# {mark} {{ cluster_name }} OCP CLUSTER MANAGED BLOCK"

  - name: SNO - Set ai_cluster_id
    set_fact:
      ai_cluster_id: "{{ create_cluster_return.json.id }}"
  when: cluster_type == "sno"

- name: MNO Cluster Creation
  block:
  - name: MNO - Populate static network configuration with controlplane nodes
    include_role:
      name: create-ai-cluster
      tasks_from: static_network_config.yml
    loop: "{{ groups['controlplane'] }}"

  - name: MNO - Populate static network configuration with worker nodes
    include_role:
      name: create-ai-cluster
      tasks_from: static_network_config.yml
    loop: "{{ groups['worker'] }}"

  - name: MNO - Create cluster
    uri:
      url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters"
      method: POST
      body_format: json
      status_code: [201]
      return_content: true
      body: {
          "name": "{{ cluster_name }}",
          "openshift_version": "{{ openshift_version }}",
          "base_dns_domain": "{{ base_dns_name }}",
          "cluster_network_cidr": "{{ cluster_network_cidr }}",
          "cluster_network_host_prefix": "{{ cluster_network_host_prefix }}",
          "service_network_cidr": "{{ service_network_cidr }}",
          "pull_secret": "{{ pull_secret | to_json }}",
          "ssh_public_key": "{{ lookup('file', ssh_public_key_file) }}",
          "vip_dhcp_allocation": "{{ vip_dhcp_allocation }}",
      }
    register: create_cluster_return

  - name: MNO - Add entries in /etc/hosts
    blockinfile:
      path: "/etc/hosts"
      backup: true
      block: |
        {{ controlplane_network_api }} api.{{ cluster_name }}.{{ base_dns_name }}
        {{ controlplane_network_api }} api-int.{{ cluster_name }}.{{ base_dns_name }}
        {% for route in etc_hosts_ingress_routes %}
        {{ controlplane_network_ingress }} {{ route }}.apps.{{ cluster_name }}.{{ base_dns_name }}
        {% endfor %}
      insertafter: "EOF"
      marker: "# {mark} {{ cluster_name }} OCP CLUSTER MANAGED BLOCK"

  - name: MNO - Set ai_cluster_id
    set_fact:
      ai_cluster_id: "{{ create_cluster_return.json.id }}"
  when: cluster_type == "mno"

- name: Restart dnsmasq after /etc/hosts update
  systemd:
    state: restarted
    name: dnsmasq
  when: controlplane_bastion_as_dns

- name: Patch cluster network settings
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/clusters/{{ ai_cluster_id }}"
    method: PATCH
    status_code: [201]
    return_content: true
    body_format: json
    body: {
        "cluster_networks":  [
          {
            "cidr": "{{ cluster_network_cidr }}",
            "cluster_id": "{{ ai_cluster_id }}",
            "host_prefix": "{{ cluster_network_host_prefix }}"
          }
        ],
        "service_networks":  [
          {
            "cidr": "{{ service_network_cidr }}",
            "cluster_id": "{{ ai_cluster_id }}",
          }
        ]
    }

# - debug:
#     msg: "{{ static_network_config }}"

- name: Create a connected infra-env
  uri:
    url: "http://{{ assisted_installer_host }}:{{ assisted_installer_port }}/api/assisted-install/v2/infra-envs"
    method: POST
    body_format: json
    status_code: [201]
    return_content: true
    body: {
        "name": "{{ cluster_name }}",
        "ssh_authorized_key": "{{ lookup('file', ssh_public_key_file) }}",
        "pull_secret": "{{ pull_secret | to_json }}",
        "static_network_config": "{{ static_network_config }}",
        "image_type": "full-iso",
        "cluster_id": "{{ ai_cluster_id }}",
        "openshift_version": "{{ openshift_version }}",
    }
  register: create_infra_env_return

- name: Set ai_infraenv_id
  set_fact:
    ai_infraenv_id: "{{ create_infra_env_return.json.id }}"

- name: Include custom manifests
  include_role:
    name: create-ai-cluster
    tasks_from: 01_manifest_update.yml
  with_items:
  - file_name: 06-kdump-master.yaml
    template_name: 06-kdump-master.yaml
    enabled: "{{ kdump_master_config }}"
  - file_name: kubeletconfig-max-pods.yml
    template_name: kubeletconfig-max-pods.yml
    enabled: "{{ kubelet_config }}"
